version: '3.8'

services:
  mysql:
    build: ./DataBase
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase/data:/var/lib/mysql
    networks:
      - mysql

  phpmyadmin:
    build: ./PhpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - phpmyadmin

  portal-tesista:
    build: ./Portal-Tesista
    container_name: portal-tesista
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - api-portal-tesista
      - keycloak
    networks:
      - portal-tesista

  api-portal-tesista:
    build: ./API-Portal-Tesista
    container_name: api-portal-tesista
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - api-portal-tesista

  api-login:
    build: ./API-login
    container_name: api-login
    ports:
      - "9090:9090"
    depends_on:
      - mysql
      - keycloak
    networks:
      - api-login

  keycloak:
    build: ./Keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8443:8443"
    volumes:
      - ./Keycloak/data:/opt/keycloak/data
      - ./certs:/etc/x509/https
    depends_on:
      - mysql
    networks:
      - keycloak
    command: ["-Djboss.http.port=8080", "-Djboss.https.port=8443", "-Djboss.https.key-store=/etc/ssl/certs/selfsigned.jks", "-Djboss.https.key-store-password=changeit"]

networks:
  portal-tesista:
    driver: bridge
  api-portal-tesista:
    driver: bridge
  api-login:
    driver: bridge
  mysql:
    driver: bridge
  phpmyadmin:
    driver: bridge
  keycloak:
    driver: bridge