version: '3.8'

services:
  mysql:
    build: ./DataBase
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase/data:/var/lib/mysql
    networks:
      - portal-tesista

  phpmyadmin:
    build: ./PhpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - portal-tesista

#  portal-tesista:
#    build: ./Portal-Tesista
#    container_name: portal-tesista
#    ports:
#      - "80:80"
#    depends_on:
#      - mysql
#      - api-portal-tesista
#      - keycloak
#    networks:
#      - portal-tesista

  api-portal-tesista:
    build: ./API-Portal-Tesista
    container_name: api-portal-tesista
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - portal-tesista

#  api-login:
#    build: ./API-login
#    container_name: api-login
#    ports:
#      - "9090:9090"
#    depends_on:
#      - mysql
#      - keycloak
#    networks:
#      - portal-tesista

  keycloak:
    build: ./Keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
    ports:
      - "8443:8443"
    volumes:
      - ./Keycloak/data:/opt/keycloak/data
      - ./certs:/etc/x509/https
    depends_on:
      - mysql
    networks:
      - portal-tesista
    command: ["-Djboss.http.port=8080", "-Djboss.https.port=8443", "-Djboss.https.key-store=/etc/ssl/certs/selfsigned.jks", "-Djboss.https.key-store-password=changeit"]
  
networks:
  portal-tesista:
    driver: bridge