server {
    listen 80;
    server_name portaltesista.me www.portaltesista.me;

    location /.well-known/pki-validation/ {
        root /var/www/html;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name portaltesista.me www.portaltesista.me;

    ssl_certificate /etc/nginx/certs/portaltesista_me.crt;
    ssl_certificate_key /etc/nginx/certs/portaltesista_me.key;
    ssl_trusted_certificate /etc/nginx/certs/portaltesista_me.ca-bundle;

    location /api-portaltesista/ {
        rewrite ^/api-portaltesista(/.*)$ $1 break;
        proxy_pass http://api-portal-tesista:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api-login/ {
        rewrite ^/api-login(/.*)$ $1 break;
        proxy_pass http://api-login:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://portal-tesista:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
